### ISSUE TITLE
Parsing and childNodes APIs don't support some HTMLBars functions

### ISSUE THREAD

**Issue by joshvfleming** [krisselden/simple-dom#17]
We've run into a couple incompatibilities between simple-dom and HTMLBars that prevent parts of our app from rendering in Node. After some digging, there appear to be two distinct issues:

1. Elements have no "innerHTML" property for parsing HTML strings, and HTMLBars expects this API to be in place, e.g.: https://github.com/tildeio/htmlbars/blob/0d883d7dba4e4e7dc476dd7b46a45781a05b6665/packages/dom-helper/lib/build-html-dom.js#L82

2. The [childNodes property of the Node class](https://github.com/krisselden/simple-dom/blob/26164c81a5347c67fe51d2aa1074bbf321410d78/lib/simple-dom/document/node.js#L142) is not array-like, but HTMLBars expects it to be in an array-like shape, e.g.: https://github.com/tildeio/htmlbars/blob/0d883d7dba4e4e7dc476dd7b46a45781a05b6665/packages/dom-helper/lib/main.js#L547

I've managed to get things working locally with this hack:

https://gist.github.com/joshvfleming/116ed8e914a17eace348

But it's not a fully viable solution, since the "childNodes" array can get out of sync with the actual child nodes.

**Comment by krisselden** [comment]
Array access is not something I will ever add, I will likely add length and optimize .item() in the same way the browser does (caches the last indexed node and traverses from there).

The above links to pieces of htmlbars considered to be browser specific, shouldn't run on the server side, and is overriden currently by fast boot.  I'd like to just make the split in htmlbars itself.  As ember leaves IE 8 behind, I'm more open to getter/setter APIs but shipping an html5 tokenizer is a bit bloated (too many named character references), the server can just keep the html string raw.

**Comment by joshvfleming** [comment]
@krisselden Yep, @wycats set me straight on this one. The actual problem seems to be here in HTMLBars:

https://github.com/krisselden/morph-range/blob/46ce468b439dbcdf4d57c19af78ad63a7ac1c331/lib/morph-range.js#L59

When we have a helper that returns SafeString, we're calling ```morph.setHTML``` directly, which bypasses the overridden ```domHelper.setMorphHTML``` and engages all the browser parsing logic.

I'll close this issue and open a new on in the correct place. Thanks.
