### ISSUE TITLE
innerHTML and outerHTML properties

### ISSUE THREAD

**Issue by speier** [krisselden/simple-dom#4]
I know this library meant to be basic/lightweight implementation, but I wondering is there any chance to add `innerHTML` and `outerHTML` properties to `Element` interface?

Currently I'm working on server-side rendering for [Riot](https://github.com/muut/riotjs) trying to use your library, but we are relying on those properties. Thanks!

**Comment by krisselden** [comment]
I'd rather make this something you can extend is #5 enough?  Let me know if this doesn't workout and what you need.  I'm also, still on the fence about supporting childNodes.  The issue is we still support IE8, not sure for how long we will but I'm wary of merging anything that requires setters/getters.  I would consider maybe including this, but making it an optional piece.

**Comment by krisselden** [comment]
Also, I've had a busy last few days, I'll try to be more timely about my response, feel free to find me on hangouts or via email to chat further.

**Comment by speier** [comment]
Thanks for your response, I vote for extending as well.

With the merge of #5 we can add missing properties and functions, for example:

```
Document.prototype.querySelectorAll = function(selector) { .. }

Object.defineProperty(Element.prototype, 'innerHTML', { .. })
Object.defineProperty(Element.prototype, 'outerHTML', { .. })
Object.defineProperty(Element.prototype, 'style', { .. })
```

However `childNodes` is still a pain, I can convert them to an array, but not sure about the performance implications. Maybe I should come up with a solution to use `childNodes` differently on the server, for example:

```
var nodes = server ? [].slice.call(node.childNodes) : node.childNodes
```

The only problem with the above is that I'd like to avoid having such differences in the code, but no idea how can solve this otherwise.

Anyway thanks for your help!

**Comment by krisselden** [comment]
What is it you need childNodes for? Maintaining a "live" collection is really not something I'm going to do, we use the removeChild and insertBefore for mutations, we don't want to bother with array splices.  If you look at a browser implementation, like the one in WebCore, children are just in the graph structure, the childNodes isn't created until you access, and isn't maintained as an array, the only thing it optimizes is caching length as you mutate it.

**Comment by speier** [comment]
It is used by [Riot](https://github.com/muut/riotjs) for mounting and reordering tags.
https://github.com/muut/riotjs/blob/dev/lib/tag/each.js#L102

**Comment by krisselden** [comment]
@speier this code would benefit from being rewritten to avoid childNodes.  The indexOf calls per loop would go away, diffing works better with a map and just rearranging the linked list.

**Comment by speier** [comment]
@krisselden my inital plan is to simple replace the above with this:
```
 var nodes = [].slice.call(root.childNodes),
     prev_index = nodes.indexOf(prev)
```
In this way it could work without changing anything else.

But I'm open for further suggestions, could you please explain your above comment what you mean more specifically? Thanks!

**Comment by speier** [comment]
@krisselden also could you please publish the latest to npm? thanks!

**Comment by krisselden** [comment]
@speier I'm sorry I missed this. Will do right away.

**Comment by krisselden** [comment]
@speier I've tagged and published, I was thinking I could provide a hook for initializing and for when children are mutated for maintaining a childNodes, I'm willing to ship a build with it, but by dom spec it is supposed to be a live collection, and splicing an array of children per mutation, during a sort on a list would be painful.

@speier my comment on the referenced code is that you just use the linked list while doing the diff.  Repeating the indexOf means you are scanning the list during each iteration, while arrays are very fast and this is fast for small things, it grows exponentially as the list grows.

**Comment by krisselden** [comment]
@speier can you chat me on google hangouts? My email is on my github profile. I'm more responsive there, github notifications are so numerous I have a hard time keeping up.

**Comment by speier** [comment]
@krisselden ok we can chat later, thanks!
